### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by torch2424** [torch2424/as-bind#1]
* [ ] Make a Dope Markdown / Wasm Vs. ES6 Benchmark / Vs. Rust (maybe not rust?)
* [ ] Make a Dope README
* [ ] Get Feedback from the team

**Comment by torch2424** [comment]
For the Markdown parser, totally just port this: https://github.com/developit/snarkdown

We also need a regex engine :p 

https://nickdrane.com/build-your-own-regex/

Other things to maybe "port":

https://github.com/aishikaty/tiny-mustache/blob/master/mustache.js

And for a typed array demo. Do a bit crusher where we pass the float PCM samples directly?

**Comment by torch2424** [comment]
closing in favor of #5
