### ISSUE TITLE
Launch TODO

### ISSUE THREAD

**Issue by torch2424** [torch2424/as-bind#5]
* [x] Fix the bugs, and finish core of Markdown parser
* [x] Create a quick demo of the markdown parser, with a debouched input field and things, and links to asbind
* [x] Have console logs show the generated HTML from the assemblyscript module (show off binding imports)

* [x] Clean up API, make `new AsBind`, in which modules have instances.
* [x] Add [speculative execution](https://en.wikipedia.org/wiki/Speculative_execution) support, E.g (if it was a string on the first run, it's probably a string again)
* [x] Add a way for users to disable the speculative execution
* [x] Write README
* [x] Add Wat files to their respective wasm files for github to pick up the repo as a wasm repo
* [x] Make sure the `as-bind` is consistent. no `asbind`
* [x] Add Travis support for when PRs are opened, tests are run
* [x] Close #2 
* [x] Write Medium Article
* [x] Write Tweet
* [x] Launch 

# Post Launch

* [ ] Add support for Custom created object classes. (Was going to do in launch, but honestly seems super complicated, and will need some help from the library team. Let's see how well the library launches first :smile:  )

**Comment by torch2424** [comment]
Decided not to debounce, as we don't want to artifically make it feel slow :thinking:

**Comment by torch2424** [comment]
Boolean support? :thinking:

**Comment by torch2424** [comment]
Boolean support? :thinking:

**Comment by torch2424** [comment]
Medium article in drafts, Tweet is in my private discord channel :smile:
